name: Publish to Docker

on:
  schedule:
    - cron: '0 0 * * 5' # Every Friday at midnight we publish an image from latest to Docker Hub.
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get current date/time in the usual format
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d.%H%M%S')"
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.pacwa.xyz/prusaslicer-novnc:latest, registry.pacwa.xyz/prusaslicer-novnc:${{ steps.date.outputs.date }}
